server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: ACE

eureka:
  client:
    # 表示是否将自己注册进eurekaServer, 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true，才能配合ribbon做负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/  # 集群版的配置
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔   默认30s
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5s的间隔   默认90s
    instance-id: receive-8802.com # 在eureka列表中显示的主机名称
    prefer-ip-address: true # 访问的路径变为ip地址