server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos地址
    sentinel:
      transport:
        #        配置sentinel的dashboard的地址
        dashboard: localhost:8080
        #        默认8179，加入被占用，会自动从8719依次+1扫描，直到找到未被占用的端口
        #        sentinel会启动一个http server与dashboard进行通信，需要占用8719端口
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
